language: php

php:
    - 5.4
    - 5.5
    - 5.6
    #- hhvm
    - nightly
    - "7.0"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        - php: nightly



before_script:
    # Prepare for automated tests
    - make automated-tests-prepare



script:
    # Check version and environment
    - make automated-tests-check

    # Run tests
    - make automated-tests-run



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/fdbd27d2391724c0231b

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
